# bot's config

token = "NjYxMTcxMzYyODU2OTYwMDEx.Xgnh0A.Qqn1o2aUQDfNRVDC39FIE3_vum4" # "ODM1NDYxODc0MTY1NjEyNTY0.YIPygA.p9Qs0LTDHWBBDtTd76ArdAOcLWY" # get yours here -> https://discord.com/developers/applications/
main_color = "0xaefe19" # the main color for all embeds
error_color = "0xfe2419" # the error color of your bot
owner_id = [583663379030212609, 476818400010829836] # the id of the bot owner

[databases]

    [databases.guilds]
    name = "s5_nebula_guilds"
    host = "172.18.0.1"
    port = 3306
    user = "u5_t8dRJiQJdt"
    password = "+6mgpn!5Tl@PySwvv9MP2h^I"

    [databases.users]
    name = "s5_nebula_users"
    host = "172.18.0.1"
    port = 3306
    user = "u5_naU3N0vQ8o"
    password = "VCqxoE+SM.ptcclOT46k!NhU"

    [databases.punishments]
    name = "s5_nebula_punishments"
    host = "172.18.0.1"
    port = 3306
    user = "u5_BTONF2QSKi"
    password = "m9Re0f.QIWbbYg@Oe8c1S8WF"